FROM openliberty/open-liberty:22.0.0.13-kernel-slim-java11-openj9-ubi
COPY --chown=1001:0  ./target/jakartaee8-starter.war /config/dropins/
COPY --chown=1001:0  ./src/main/liberty/config/server.xml /config/
RUN configure.sh
