name: dockerize

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build Docker images
        run: |
          # see: https://www.prestonlamb.com/blog/creating-a-docker-image-with-github-actions
           docker build -t hantsy/jakartaee8-starter-payara -f ./Dockerfile.payara .
           docker build -t hantsy/jakartaee8-starter-wildfly -f ./Dockerfile.wildfly .
           docker build -t hantsy/jakartaee8-starter-openliberty -f ./Dockerfile.openliberty .
      - name: Pushing Docker images
        run: |
           docker push hantsy/jakartaee8-starter-payara
           docker push hantsy/jakartaee8-starter-wildfly
           docker push hantsy/jakartaee8-starter-openliberty
